#  Города
## Возвращает список городов
GET http://localhost:5000/cities HTTP/1.1
Content-Type: application/json

###

## Создает город на основе переданных данных
POST http://localhost:5000/cities HTTP/1.1
Content-Type: application/json

{
  "name": "Moscow",
  "coords": {
    "lat": 55.7558,
    "long": 37.6173
  }
}

###
