# Пользователи
## Регистрирует нового пользователя
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Michael Surname",
  "email": "michae@test.net",
  "avatar": "avatar.png",
  "pass": "pass",
  "type": "general"
}

###

## Авторизует пользователя на основе логина и пароля
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "author4@example.com",
  "pass": "pass"
}

###

## Загружает изображение аватара пользователя
POST http://localhost:5000/users/647e1ea88507534f70eaae84/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="123.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/123.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
