# Пользователи
## Регистрирует нового пользователя
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Ava Test",
  "email": "avatar-test@test.net",
  "pass": "123456",
  "type": "pro"
}

###

## Авторизует пользователя на основе логина и пароля
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "michae@test.net",
  "pass": "pass"
}

###

##  Проверяет аутентификацию пользователя
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer 123

###

## Загружает изображение аватара пользователя
POST http://localhost:5000/users/647e1ea88507534f70eaae84/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="123.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/123.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
