# Пользователи
## Регистрирует нового пользователя
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Michael Surname",
  "email": "michae@test.net",
  "avatar": "avatar.png",
  "pass": "pass",
  "type": "general"
}

###

## Авторизует пользователя на основе логина и пароля
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "michae@test.net",
  "pass": "pass"
}

###

##  Проверяет аутентификацию пользователя
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer 123

###
