# Предложения об аренде
## Возвращает список предложений об аренде
GET http://localhost:5000/rents HTTP/1.1
Content-Type: application/json

###

## Возвращает информацию о предложении об аренде
GET http://localhost:5000/rents/648196cf1ca25c81b7bbf621 HTTP/1.1
Content-Type: application/json

###

## Создает предложение об аренде на основе переданных данных
POST http://localhost:5000/rents HTTP/1.1
Content-Type: application/json
Authorization: Bearer 123

{
  "title": "Cute central flat with modern design",
  "description": "Cute central flat with modern design",
  "city": "6482338ebd19612260152a87",
  "isPremium": false,
  "type": "room",
  "rooms": 2,
  "guests": 3,
  "price": 1200,
  "facilities": [
    "Laptop friendly workspace",
    "Washer"
  ]
}

###

## Удаление предложения об аренде
DELETE http://localhost:5000/rents/647e1ea88507534f70eaae8a HTTP/1.1
Content-Type: application/json
Authorization: Bearer 123

###

## Редактирование предложения об аренде
PATCH http://localhost:5000/rents/647e1ea88507534f70eaae9e HTTP/1.1
Content-Type: application/json
Authorization: Bearer 123

{
  "title": "Cute central flat with ancient designs",
  "rooms": 8
}

###

## Возвращает комментарии к предложению об аренде
GET http://localhost:5000/rents/647e1ea88507534f70eaae8a/comments HTTP/1.1
Content-Type: application/json

###

## Возвращает список предложений об аренде, отсортированный по возрастанию по рейтингу
GET http://localhost:5000/rents/sort/top-rated HTTP/1.1
Content-Type: application/json

###

## Возвращает список предложений об аренде, отсортированный по возрастанию по количеству комментариев
GET http://localhost:5000/rents/sort/popular HTTP/1.1
Content-Type: application/json

###

## Загружает изображение превью предложения об аренде
POST http://localhost:5000/rents/647e1ea88507534f70eaae9e/preview HTTP/1.1
Authorization: Bearer 123
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="1.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загружает изображения для предложения об аренде
POST http://localhost:5000/rents/647e1ea88507534f70eaae9e/images HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImF2YXRhci10ZXN0QHRlc3QubmV0IiwiaWQiOiI2NDk2ZjJhNjJiY2YzMjA4ZGEwY2UxNDUiLCJpYXQiOjE2ODc2MjAwMjMsImV4cCI6MTY4Nzc5MjgyM30.qKmmVN7DWfiSon8Dc8tgGJHl6OaS7K1Qxg5mBBTQj_4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="3.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="4.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/4.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="5.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/5.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="6.png"
Content-Type: image/png

< /Users/ekateric/Documents/screenshots/6.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
